colaraz/colaraz-theme

lms/templates/dashboard.html, lms/templates/header/user_dropdown.html
This PR is related to [https://edlyio.atlassian.net/browse/EDE-405](https://edlyio.atlassian.net/browse/EDE-405)
The links has been updated on user dashboard.
Some extra user information has been displayed on user dashboard.
**Note:**
To make this code work:
You will need to add the following variable in the site configurations of studio and lms
```
{
...
"CMS_BASE":"<your studio base url>"
...
}
```
=> Integrate course page

lms/templates/dashboard.html, lms/templates/main.html
This PR is related to [https://edlyio.atlassian.net/browse/EDE-428](https://edlyio.atlassian.net/browse/EDE-428)
**PR description**
The sidebar has been moved to **main.html**
The **active** status of links has been managed
=> Move sidebar to main.html from dashboard.html

lms/templates/main.html
This PR is related to [https://edlyio.atlassian.net/browse/EDE-432](https://edlyio.atlassian.net/browse/EDE-432)
Update the studio link anchor tag to create an absolute link upon clicking.
=> Update studio link

cms/templates/widgets/user_dropdown.html, lms/templates/header/user_dropdown.html, lms/templates/user_dropdown.html
=> add colaraz logout url

cms/templates/widgets/user_dropdown.html
https://edlyio.atlassian.net/browse/EDE-427
=> adding lms protocol

cms/templates/widgets/user_dropdown.html
https://edlyio.atlassian.net/browse/EDE-427
=> adding protocol to lms_base

lms/templates/header/user_dropdown.html, lms/templates/main.html
https://edlyio.atlassian.net/browse/EDE-444
=> Add/Update User Fields

lms/templates/header/header.html, lms/templates/header/navbar-logo-header.html
[EDE-453](https://edlyio.atlassian.net/browse/EDE-453)
Dynamically update navbar urls
=> update navbar urls

lms/templates/course_details_sidebar.html, lms/templates/courseware/course_about.html
This PR is related to [EDE-443](https://edlyio.atlassian.net/browse/EDE-443)
A new **course_details_sidebar.html** has been added containing which is responsible to show course-related details.
Moreover, studio link and start date are also updated on the course about page.
**Sidebar**
**Updated studio link**
=> EDE-443 Integrate course details sidebar

lms/static/sass/course/_course-about.scss, lms/static/sass/course/_dashboard.scss, lms/static/sass/discussion/_layouts.scss, lms/static/sass/discussion/views/_response.scss, lms/templates/course_details_sidebar.html, lms/templates/dashboard.html, lms/templates/main.html
Client feedback for Colaraz theme
**JIRA:** 
[EDE-451](https://edlyio.atlassian.net/browse/EDLY-451)
=> Client feedback for colaraz theme

colaraz/cms/static/sass/partials/cms/theme/_variables-v2.scss, colaraz/cms/static/sass/shared-v2/_header.scss, colaraz/cms/templates/base.html, colaraz/cms/templates/widgets/header.html
=> Studio Header platform name added

colaraz/cms/static/sass/shared-v2/_header.scss, colaraz/cms/templates/widgets/header.html, colaraz/lms/static/sass/course/_course-about.scss, colaraz/lms/static/sass/course/_dashboard.scss, colaraz/lms/static/sass/course/layout/_course-instructor-tab.scss, colaraz/lms/static/sass/course/layout/_courseware_preview.scss, colaraz/lms/static/sass/course/wiki/_wiki.scss, colaraz/lms/static/sass/discussion/views/_response.scss, colaraz/lms/static/sass/shared-v2/_header.scss, colaraz/lms/templates/courseware/progress.html
[https://edlyio.atlassian.net/browse/EDE-451](https://edlyio.atlassian.net/browse/EDE-451)
=> Button's text, styles and layout implemented according to client feedback

colaraz/cms/templates/widgets/header.html, colaraz/lms/templates/header/header.html, colaraz/lms/templates/header/user_dropdown.html
https://edlyio.atlassian.net/browse/EDE-453
=> user role based urls

colaraz/cms/static/sass/shared-v2/_header.scss, colaraz/cms/templates/widgets/header.html, colaraz/lms/static/sass/course/_course-about.scss, colaraz/lms/static/sass/course/_dashboard.scss, colaraz/lms/static/sass/course/layout/_course-instructor-tab.scss, colaraz/lms/static/sass/course/layout/_courseware_preview.scss, colaraz/lms/static/sass/course/wiki/_wiki.scss, colaraz/lms/static/sass/discussion/views/_response.scss, colaraz/lms/static/sass/shared-v2/_header.scss, colaraz/lms/templates/courseware/progress.html, colaraz/lms/templates/header/header.html, colaraz/lms/templates/header/user_dropdown.html
This PR contains all the code done till release-2020-05-12:
* [EDE-473](https://edlyio.atlassian.net/browse/EDE-473)
* [EDE-453](https://edlyio.atlassian.net/browse/EDE-453)
* [EDE-451](https://edlyio.atlassian.net/browse/EDE-451)
=> release-2020-05-12

colaraz/cms/templates/widgets/header.html, colaraz/cms/templates/widgets/user_dropdown.html, colaraz/lms/templates/header/header.html, colaraz/lms/templates/header/user_dropdown.html
[EDE-485](https://edlyio.atlassian.net/browse/EDE-485)
A few more urls are being added in user links API, so this Pr maps those urls as well as also refactor code a bit.
=> refactoring and mapping colaraz role based urls

colaraz/cms/static/sass/shared-v2/_header.scss, colaraz/lms/static/sass/_theme-style.scss, colaraz/lms/static/sass/course/_dashboard.scss, colaraz/lms/static/sass/course/_privileges.scss, colaraz/lms/static/sass/partials/lms/theme/_variables.scss, colaraz/lms/static/sass/shared-v2/_header.scss, colaraz/lms/templates/main.html
**JIRA:** 
https://edlyio.atlassian.net/browse/EDE-451
=> Client feedback for Course privileges

colaraz/cms/static/sass/shared-v2/_header.scss, colaraz/lms/static/sass/course/_privileges.scss, colaraz/lms/static/sass/shared-v2/_header.scss, colaraz/lms/templates/courseware/course_about.html
=> Course Privileges view updates

colaraz/lms/static/sass/course/_privileges.scss, colaraz/lms/static/sass/discussion/_layouts.scss, colaraz/lms/static/sass/shared-v2/_header.scss
https://edlyio.atlassian.net/browse/EDE-451
=> Pagination and instructor images updated

colaraz/cms/static/js/header.js, colaraz/cms/templates/widgets/header.html, colaraz/lms/static/js/header/header.js, colaraz/lms/templates/header/navbar-authenticated.html
[EDE-459](https://edlyio.atlassian.net/browse/EDE-459)
Add a popup window that opens on invite friend button click.
=> Add invite friend window popup

colaraz/cms/static/js/header.js, colaraz/cms/static/sass/_layouts.scss, colaraz/cms/static/sass/partials/cms/theme/_variables-v1.scss, colaraz/cms/static/sass/shared-v2/_dashboard.scss, colaraz/cms/static/sass/shared-v2/_header.scss, colaraz/lms/static/js/header/header.js, colaraz/lms/static/sass/course/_dashboard.scss, colaraz/lms/static/sass/course/layout/_course-instructor-tab.scss, colaraz/lms/static/sass/shared-v2/_header.scss, colaraz/lms/templates/instructor/instructor_dashboard_2/course_info.html
**JIRA:** 
https://edlyio.atlassian.net/browse/EDE-512
=> Client CMS feedback implemented

colaraz/cms/static/sass/_layouts.scss, colaraz/cms/static/sass/shared-v2/_header.scss, colaraz/lms/static/js/header/header.js, colaraz/lms/static/sass/base/_mixins.scss, colaraz/lms/static/sass/course/_dashboard.scss, colaraz/lms/static/sass/course/layout/_course-instructor-tab.scss, colaraz/lms/static/sass/course/layout/_courseware_preview.scss, colaraz/lms/static/sass/shared-v2/_form-elements.scss, colaraz/lms/static/sass/shared-v2/_header.scss
**JIRA:** 
https://edlyio.atlassian.net/browse/EDE-512
=> Feedback Implementation

colaraz/lms/static/sass/course/_course-about.scss, colaraz/lms/static/sass/course/layout/_course-instructor-tab.scss, colaraz/lms/static/sass/discussion/_layouts.scss, colaraz/lms/templates/courseware/progress.html, colaraz/lms/templates/instructor/instructor_dashboard_2/instructor_dashboard_2.html
**JIRA:** 
https://edlyio.atlassian.net/browse/EDE-533
=> Update header for course pages

colaraz/cms/static/sass/_layouts.scss, colaraz/cms/static/sass/_theme-style.scss, colaraz/cms/static/sass/base/_mixins.scss, colaraz/cms/static/sass/elements/_form.scss, colaraz/cms/static/sass/shared-v2/_dashboard.scss, colaraz/cms/templates/asset_index.html, colaraz/cms/templates/certificates.html, colaraz/cms/templates/checklists.html, colaraz/cms/templates/course_info.html, colaraz/cms/templates/course_outline.html, colaraz/cms/templates/edit-tabs.html, colaraz/cms/templates/group_configurations.html, colaraz/cms/templates/manage_users.html, colaraz/cms/templates/manage_users_lib.html, colaraz/cms/templates/settings.html, colaraz/cms/templates/settings_advanced.html, colaraz/cms/templates/settings_graders.html, colaraz/cms/templates/textbooks.html, colaraz/cms/templates/videos_index.html
Templates files are imported from edX-platoform and only course titles are added.
```<span class="text">${context_course.display_name_with_default}</span> ```
**JIRA:** 
https://edlyio.atlassian.net/browse/EDE-534
=> [Studio] Add course title to pages

colaraz/lms/templates/header/navbar-authenticated.html
**Story Link**
[EDE-528](https://edlyio.atlassian.net/browse/EDE-528)
**Description**
updated the fetching way of invitation url
=> Grab invite a friend window link from User Links API

colaraz/lms/templates/courseware/progress.html, colaraz/lms/templates/instructor/instructor_dashboard_2/instructor_dashboard_2.html
This PR is related to [https://edlyio.atlassian.net/browse/COL-84](https://edlyio.atlassian.net/browse/COL-84)
This PR course image has been integrated with the `programs` and `instructors` tab.
**Programs Page**
**Instructors Page**
=> Integrate course header for progress and instructor tab

colaraz/cms/static/js/header.js, colaraz/cms/templates/base.html, colaraz/cms/templates/widgets/header.html, colaraz/lms/static/js/header/header.js, colaraz/lms/templates/header/navbar-authenticated.html, colaraz/lms/templates/main.html
[EDE-533](https://edlyio.atlassian.net/browse/EDE-533)
This PR contains code regarding the integration of Colaraz Job Alerts API.
We need to add the following variables in lms.env.json and cms.env.json
```
"COLARAZ_JOB_ALERTS" : {
"FETCH_URL": "http://www.colaraz.net/Resources/wsResources.asmx/GetJobAlertsByEmail",
"MARK_URL": "http://www.colaraz.net/Resources/wsResources.asmx/JobNotificationMarkReadByEmail",
"REFRESH_TIME_MILLISECONDS": "30000"
}
```
=> job alerts api integration

colaraz/cms/static/js/header.js
[EDE-533](https://edlyio.atlassian.net/browse/EDE-533)
This PR contains code regarding the integration of Colaraz Job Alerts API.
We need to add the following variables in lms.env.json and cms.env.json
```
"COLARAZ_JOB_ALERTS" : {
"FETCH_URL": "http://www.colaraz.net/Resources/wsResources.asmx/GetJobAlertsByEmail",
"MARK_URL": "http://www.colaraz.net/Resources/wsResources.asmx/JobNotificationMarkReadByEmail",
"REFRESH_TIME_MILLISECONDS": "30000"
}
```
=> FIX: setInterval function for job_alerts api

colaraz/cms/templates/base.html
Story Link
[COL-10](https://edlyio.atlassian.net/browse/COL-10)
Description
added the checks to avoid viewing course privileges to non-role_manager on studio site
=> Apply checks on course access roles on studio sidebar

colaraz/lms/static/sass/_theme-style.scss, colaraz/lms/static/sass/multicourse/_dashboard.scss
**JIRA:** 
https://edlyio.atlassian.net/browse/COL-105
=> View Certificate button styles updated

colaraz/cms/templates/export.html, colaraz/cms/templates/export_git.html, colaraz/cms/templates/import.html
**JIRA:** 
https://edlyio.atlassian.net/browse/COL-106
=> Courses name added in studio for import and export pages

colaraz/cms/static/js/header.js, colaraz/cms/static/sass/shared-v2/_header.scss, colaraz/cms/templates/widgets/header.html, colaraz/lms/static/js/header/header.js
**JIRA:** 
https://edlyio.atlassian.net/browse/COL-106
=> Drop Alert drop down updated

colaraz/cms/static/sass/base/_mixins.scss, colaraz/lms/static/sass/base/_mixins.scss
**JIRA:** 
https://edlyio.atlassian.net/browse/COL-106
=> Button Alignment

colaraz/lms/static/sass/course/layout/_courseware_preview.scss, colaraz/lms/static/sass/shared-v2/_form-elements.scss, colaraz/lms/templates/main.html
**JIRA:** 
https://edlyio.atlassian.net/browse/COL-56
=> Feedback from QA

colaraz/lms/static/sass/course/layout/_courseware_preview.scss, colaraz/lms/static/sass/discussion/_layouts.scss, colaraz/lms/static/sass/discussion/views/_response.scss
**JIRA:** 
https://edlyio.atlassian.net/browse/COL-112
=> Enable search on course tabs on LMS

colaraz/cms/static/sass/_layouts.scss, colaraz/lms/static/sass/course/_dashboard.scss, colaraz/lms/static/sass/course/layout/_course-instructor-tab.scss, colaraz/lms/static/sass/course/layout/_courseware_preview.scss
Fix course handout image on LMS side
The wrong color appears on focus when the user Bookmarked any problem
Incomplete table is appearing on the "Show Task Status" button
List of the enrolled students is out of shape. "Reports Available for Download" section header is out of shape
Open Response column name "Assessment" is not completely visible
Youtube introductory video is not responsive
**JIRA:** 
https://edlyio.atlassian.net/browse/COL-128
https://edlyio.atlassian.net/browse/COL-129
https://edlyio.atlassian.net/browse/COL-130
https://edlyio.atlassian.net/browse/COL-131
https://edlyio.atlassian.net/browse/COL-132
https://edlyio.atlassian.net/browse/COL-133
=> Fix UI issues for LMS and CMS

colaraz/cms/templates/widgets/user_dropdown.html, colaraz/lms/templates/main.html
https://edlyio.atlassian.net/browse/COL-141
Show course studio link to everyone having at least one of staff or instructor or course creator role. And implementing a check regarding LMS_BASE configuration.
=> show studio link to all users having at-least one staff or instructor role

colaraz/cms/static/js/header.js, colaraz/cms/templates/base.html, colaraz/lms/static/js/header/header.js, colaraz/lms/templates/main.html
https://edlyio.atlassian.net/browse/COL-142
Add ENABLED flag in Notifications and Job Alerts APIs
=> Add ENABLED flag in Notifications and Job Alerts APIs

colaraz/lms/static/sass/course/_course-about.scss
Enroll button disturbed when program set to professional in ecommerce
**JIRA:** 
https://edlyio.atlassian.net/browse/COL-156
**Merge deadline:**
=> Enroll button disturbed when program set to professional in ecommerce

colaraz/lms/static/js/discussion/colaraz_discussion_filters.js, colaraz/lms/templates/main.html
Story Links
[COL-125](https://edlyio.atlassian.net/browse/COL-125)
PR Links
[Colaraz Edx-Platform](https://github.com/colaraz/edx-platform/pull/82)
description: 
added search functionality for all the posts done on a particular course which is displayed in the all discussion dropdown.
=> Search all Posts in Discussion Forum

colaraz/lms/static/sass/_overrides.scss
https://edlyio.atlassian.net/browse/COL-147
Temporay fix for verified course enrollment page
Before:
After:
=> temporay fix for verified course enrollment page

colaraz/lms/templates/main.html
HotFix: User's Profile isn't present while Account creation so we have to check if the user has an account or not.
=> Fixing user creation issue

colaraz/lms/static/js/discussion/colaraz_discussion_utils.js, colaraz/lms/templates/main.html
This PR contains: 
* #75 HotFix for account creations
=> release-2020-07-09.1

colaraz/lms/static/js/discussion/colaraz_discussion_filters.js, colaraz/lms/static/js/discussion/colaraz_discussion_utils.js, colaraz/lms/static/sass/discussion/views/_response.scss, colaraz/lms/templates/main.html
This PR is related to [https://edlyio.atlassian.net/browse/COL-159](https://edlyio.atlassian.net/browse/COL-159)
Because of the redesigning of `discussion` page, the `follow post` functionality was broken. Now it has been fixed.
**Related PR**
This PR is dependent on the PR from colaraz/edx-platform
[https://github.com/colaraz/edx-platform/pull/88](https://github.com/colaraz/edx-platform/pull/88)
=> COL-159 Add follow post functionality

colaraz/lms/static/js/discussion/colaraz_discussion_filters.js, colaraz/lms/static/js/discussion/colaraz_discussion_utils.js, colaraz/lms/static/sass/discussion/_layouts.scss
Ticket link
[COL-167](https://edlyio.atlassian.net/browse/COL-167)
Colaraz Platform link:
https://github.com/colaraz/edx-platform/pull/89/files
Description:
QA issues resolved except point 12 ( All topics scrollbar) although I have added scrollbar on all discussions and posts I'm following dropdown.`
=> Discussion Filter QA issues Resolved

colaraz/lms/static/js/discussion/colaraz_discussion_filters.js, colaraz/lms/templates/main.html
This PR is related to [https://edlyio.atlassian.net/browse/COL-174](https://edlyio.atlassian.net/browse/COL-174)
Previously, we were loading discussions on every page load of `edx`. Now we have fixed that issue.
=> Fix duplicate discussion settings error

colaraz/lms/static/js/discussion/colaraz_discussion_utils.js, colaraz/lms/templates/main.html
This PR is related to [https://edlyio.atlassian.net/browse/COL-174](https://edlyio.atlassian.net/browse/COL-174)
Previously, the voting and post following functionality wasn't working for `unit level discussion`. Now this functionality has been added.
**Related PR**
[https://github.com/colaraz/edx-platform/pull/92](https://github.com/colaraz/edx-platform/pull/92)
=> COL-174 Fix unit level discussion issue

colaraz/lms/templates/instructor/instructor_dashboard_2/membership.html, colaraz/lms/templates/instructor/instructor_dashboard_2/student_admin.html
This PR is related to [https://edlyio.atlassian.net/browse/COL-173](https://edlyio.atlassian.net/browse/COL-173)
Removing usernames from the instructor dashboard.
**Related PR**
[https://github.com/colaraz/edx-platform/pull/91](https://github.com/colaraz/edx-platform/pull/91)
=> COL-173 Remove username from membership and student admin tabs of instructor

colaraz/cms/static/sass/shared-v2/_header.scss, colaraz/lms/static/sass/shared-v2/_header.scss
Relocating the Notification Counter
**JIRA:** 
https://edlyio.atlassian.net/browse/COL-169
=> Relocating the Notification Counter

colaraz/lms/static/sass/discussion/views/_response.scss
Remove icons from discussion page
**JIRA:** 
https://edlyio.atlassian.net/browse/COL-170
=> Remove icons from discussion page

colaraz/lms/static/js/discussion/colaraz_discussion_filters.js, colaraz/lms/static/sass/discussion/_layouts.scss, colaraz/lms/static/sass/discussion/views/_response.scss
**JIRA:** 
https://edlyio.atlassian.net/browse/COL-175
=> Discussion Filters UI styles update

colaraz/lms/static/js/discussion/colaraz_discussion_filters.js, colaraz/lms/static/sass/discussion/_layouts.scss, colaraz/lms/static/sass/discussion/views/_response.scss
This PR is related to [https://edlyio.atlassian.net/browse/COL-179](https://edlyio.atlassian.net/browse/COL-179)
This minor release includes:
#87 Discussion Dropdowns, Scrollbar, and load more button fix
#88 Use let to create the variable
#90 Scroll issue fixes
=> release-2020-07-15.1

colaraz/lms/static/sass/_overrides.scss, colaraz/lms/static/sass/course/_dashboard.scss, colaraz/lms/static/sass/discussion/_layouts.scss
Layout and design updates for enroll page of verified courses
**JIRA:** 
https://edlyio.atlassian.net/browse/COL-147
=> Layout and design updates for enroll page of verified courses

colaraz/cms/static/sass/_theme-style.scss, colaraz/cms/static/sass/elements/_system-feedback.scss
Update deletion pop up layout of Studio pages
**JIRA:** 
https://edlyio.atlassian.net/browse/COL-185
=> Update deletion pop up layout of Studio pages

colaraz/cms/static/sass/_theme-style.scss, colaraz/cms/static/sass/elements/_system-feedback.scss, colaraz/lms/static/sass/_overrides.scss, colaraz/lms/static/sass/course/_dashboard.scss, colaraz/lms/static/sass/discussion/_layouts.scss
This release contains the following PRs:
* #91 Adding layout for Verified course enrollment page
* #92 Update deletion popup layout on studio
=> release-2020-07-24

colaraz/lms/templates/dashboard/_dashboard_course_listing.html
This PR is related to [https://edlyio.atlassian.net/browse/COL-189](https://edlyio.atlassian.net/browse/COL-189)
=> COL-189 Hide learn more about certificates link

colaraz/lms/static/js/discussion/colaraz_discussion_filters.js, colaraz/lms/static/js/discussion/colaraz_discussion_utils.js
Story Link
[Col-175](https://edlyio.atlassian.net/browse/COL-175)
description: updated the checks to remove and add the element
PR link to platform: https://github.com/colaraz/edx-platform/pull/106
=> No More Posts element glitch fix

colaraz/ecommerce/colaraz-ecommerce/static/css/.gitignore
This PR is related to [https://edlyio.atlassian.net/browse/COL-202](https://edlyio.atlassian.net/browse/COL-202)
Fix directory issue.
=> Fix css directory issue

colaraz/lms/templates/dashboard/_dashboard_certificate_information.html, colaraz/lms/templates/dashboard/_dashboard_course_listing.html
This PR is related to [https://edlyio.atlassian.net/browse/COL-197](https://edlyio.atlassian.net/browse/COL-197)
We have replaced manual user ID verification with an automatic user ID verification. But there are still some places on LMS which needs to be updated according to this change.
=> COL-197 Update ID verification message on lms dahsboard

colaraz/ecommerce/colaraz-ecommerce/static/sass/partials/components/_navbar.scss, colaraz/ecommerce/colaraz-ecommerce/templates/edx/partials/_base_navbar.html, colaraz/lms/templates/dashboard/_dashboard_certificate_information.html
This PR is related to [https://edlyio.atlassian.net/browse/COL-204](https://edlyio.atlassian.net/browse/COL-204)
In this PR we have updated the ecommerce navbar. 
In the PR [https://github.com/colaraz/colaraz-theme/pull/101/files](https://github.com/colaraz/colaraz-theme/pull/101/files) we used wrong commenting syntax for **mako** templates which was causing a build failure. Now, this issue has also been fixed in this PR.
**Old navbar**
**New navbar for superuser**
**New navbar for normal user**
=> COL-204 Remove username from ecommerce navbar and fix commenting

colaraz/lms/static/sass/discussion/_layouts.scss, colaraz/lms/templates/student_account/login_and_register.html
Add loader to /register page
**JIRA:** 
https://edlyio.atlassian.net/browse/COL-200
**Merge deadline:**
=> Loader to login/register page keeps show

colaraz/lms/static/sass/certificates.scss, colaraz/lms/templates/certificates/_accomplishment-footer.html, colaraz/lms/templates/certificates/accomplishment-base.html, colaraz/lms/templates/certificates/valid.html
**JIRA:** 
https://edlyio.atlassian.net/browse/COL-214
=> Certificate header and footer designing

colaraz/lms/static/sass/certificates.scss, colaraz/lms/templates/certificates/_accomplishment-footer.html, colaraz/lms/templates/certificates/accomplishment-base.html, colaraz/lms/templates/certificates/valid.html
https://edlyio.atlassian.net/browse/COL-219
This release contains the following PRs:
* #106 Certificate Footer Designing
=> release-2020-08-17

colaraz/cms/templates/widgets/header.html, colaraz/lms/templates/header/header.html
Finance link updated as per db value. 
[COL-221]: https://edlyio.atlassian.net/browse/COL-221
=> [COL-221] API links for header, link updated

colaraz/lms/static/sass/course/layout/_courseware_preview.scss
**JIRA:** 
https://edlyio.atlassian.net/browse/COL-252
=> smaller font size

colaraz/lms/templates/instructor/instructor_dashboard_2/membership.html
**Removed Title Edly from Bulk Enrollment**
Story Link : [COl-255](https://edlyio.atlassian.net/browse/COL-255?atlOrigin=eyJpIjoiNDAwYTIyNzdiZjQ5NDZjNjlhMThiNGZjZmIwYzY3Y2EiLCJwIjoiaiJ9)
**Description**
Removed the title 'Edly' from text and replaced the underline excel file with a new one.
These Titles are edited.
=> Removed title Edly

colaraz/lms/templates/ace_common/edx_ace/common/base_body.html
Removed "Mailing Address"
Story: [COL-273](https://edlyio.atlassian.net/browse/COL-273?atlOrigin=eyJpIjoiOTUwMzc2NjQ1YTcwNGRmNDkwZjM5NDA0ZjE5OTlhNzAiLCJwIjoiaiJ9)
Description:
Removed the dangling text "Our mailing address is" from email template.
=> Removed mailing address

colaraz/lms/static/js/header/header.js
**Description**
https://edlyio.atlassian.net/browse/COL-271
Hides the loader when page assets HTML, CSS, and javascript are loaded and the page is ready to use.
=> Hide loader on page ready

colaraz/lms/static/js/header/header.js
It includes the following changes
- https://edlyio.atlassian.net/browse/COL-279
- https://edlyio.atlassian.net/browse/COL-293
=> Release 25-03-2021

colaraz/lms/static/sass/course/layout/_courseware_preview.scss, colaraz/lms/templates/ace_common/edx_ace/common/base_body.html
Timed exam, sticky header, and main Email template background
**JIRA:** 
https://edlyio.atlassian.net/browse/COL-295
https://edlyio.atlassian.net/browse/COL-297
=> Timed exam, sticky header and main Email template background

colaraz/cms/static/js/header.js, colaraz/cms/templates/base.html, colaraz/lms/static/js/header/header.js, colaraz/lms/templates/main.html
Ticket: https://edlyio.atlassian.net/browse/COL-306
- Add hidden iframe to `postmessages` to IDP to check session
- Add auto-logout based on session existence in colaraz IDP.
- Copy pasted same code in studio, which I don't know why needed. :
=> Add autologout functionality

colaraz/cms/static/js/header.js, colaraz/lms/static/js/header/header.js
- add `setTimout` for first time function call.
- Refactoring code
=> fix for first time interval to call IDP

colaraz/cms/static/js/header.js, colaraz/lms/static/js/header/header.js
=> col-306 fix for first internal

colaraz/cms/static/js/header.js, colaraz/cms/templates/base.html, colaraz/lms/static/js/header/header.js, colaraz/lms/static/sass/course/layout/_courseware_preview.scss, colaraz/lms/templates/ace_common/edx_ace/common/base_body.html, colaraz/lms/templates/main.html
Merging `develop` back to `master`.
=> Release candidate

colaraz/lms/static/sass/_overrides.scss
=> fix buttons overlay

colaraz/cms/templates/manage_users_lib.html
Fixed after comparing with ironwood.master.
=> fix user access page

colaraz/cms/templates/import.html
pull changes from `ironwood.master`
=> fix library import export

colaraz/cms/templates/export.html
=> fix export.html

colaraz/cms/templates/base.html, colaraz/lms/templates/main.html
Change logout url in the code which is responsible to keep the edX session consistent with colaraz IdP
=> Change logout url

colaraz/lms/static/sass/course/layout/_courseware_preview.scss
Timed Exams - Sticky header for timer
=> Timed Exams - Sticky header for timer

colaraz/lms/static/sass/course/layout/_courseware_preview.scss
=> Timed Exams - Sticky header for timer feedback
